/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EditorTexto;

/**
 *
 * @author nicol
 */
public class EditorDeTexto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditorDeTexto.class.getName());
 private boolean documentoModificado = false; 
    /**
     * Creates new form EditorDeTexto
     */
    public EditorDeTexto() {
        initComponents();
    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            salirActionPerformed(null);
        }
    });
    txtEditor.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) { documentoModificado = true; }
        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) { documentoModificado = true; }
        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) { documentoModificado = true; }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEditor = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        editar = new javax.swing.JMenu();
        copiar = new javax.swing.JMenuItem();
        cortar = new javax.swing.JMenuItem();
        pegar = new javax.swing.JMenuItem();
        fuente = new javax.swing.JMenu();
        negrita = new javax.swing.JMenuItem();
        cursiva = new javax.swing.JMenuItem();
        color = new javax.swing.JMenu();
        colorFondo = new javax.swing.JMenuItem();
        colorLetra = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtEditor.setColumns(20);
        txtEditor.setRows(5);
        jScrollPane1.setViewportView(txtEditor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        archivo.setText("archivo");

        abrir.setText("abrir");
        abrir.addActionListener(this::abrirActionPerformed);
        archivo.add(abrir);

        guardar.setText("guardar");
        guardar.addActionListener(this::guardarActionPerformed);
        archivo.add(guardar);

        salir.setText("salir");
        salir.addActionListener(this::salirActionPerformed);
        archivo.add(salir);

        jMenuBar1.add(archivo);

        editar.setText("editar");

        copiar.setText("copiar");
        copiar.addActionListener(this::copiarActionPerformed);
        editar.add(copiar);

        cortar.setText("cortar");
        cortar.addActionListener(this::cortarActionPerformed);
        editar.add(cortar);

        pegar.setText("pegar");
        editar.add(pegar);

        fuente.setText("fuente");

        negrita.setText("negrita");
        negrita.addActionListener(this::negritaActionPerformed);
        fuente.add(negrita);

        cursiva.setText("cursiva");
        cursiva.addActionListener(this::cursivaActionPerformed);
        fuente.add(cursiva);

        editar.add(fuente);

        color.setText("color ");

        colorFondo.setText("fondo");
        colorFondo.addActionListener(this::colorFondoActionPerformed);
        color.add(colorFondo);

        colorLetra.setText("letra");
        colorLetra.addActionListener(this::colorLetraActionPerformed);
        color.add(colorLetra);

        editar.add(color);

        jMenuBar1.add(editar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
    javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
    javax.swing.filechooser.FileNameExtensionFilter filtro =
    new javax.swing.filechooser.FileNameExtensionFilter("Solo documentos de texto", "txt");
    fc.setFileFilter(filtro);

    if (fc.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION){
        java.io.File archivo = fc.getSelectedFile();
        try{ String contenido = new String(java.nio.file.Files.readAllBytes(archivo.toPath()));
            txtEditor.setText(contenido);
            setTitle("Documento abierto: " + archivo.getAbsolutePath());
        }catch (java.io.IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al abrir el archivo: ");
        }
    }
    }//GEN-LAST:event_abrirActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
       javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
if (fc.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
    java.io.File f = fc.getSelectedFile();
    try (java.io.PrintWriter pw = new java.io.PrintWriter(f)) {
        pw.print(txtEditor.getText());
        setTitle("Documento guardado: " + f.getAbsolutePath());
    } catch (java.io.IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar");
    }
}
    }//GEN-LAST:event_guardarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
if (documentoModificado) {
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "El documento tiene cambios sin guardar. ¿Desea salir de todas formas?",
            "Confirmar salida",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (confirmacion != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }
    }
    System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void colorFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorFondoActionPerformed
       java.awt.Color colorSeleccionado = javax.swing.JColorChooser.showDialog(
        this, "Seleccionar color de fondo", txtEditor.getBackground()
    );
    if (colorSeleccionado != null) {
        txtEditor.setBackground(colorSeleccionado);
    }
    }//GEN-LAST:event_colorFondoActionPerformed

    private void colorLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorLetraActionPerformed
        java.awt.Color colorSeleccionado = javax.swing.JColorChooser.showDialog(
        this, "Seleccionar color de letra", txtEditor.getForeground()
    );
    if (colorSeleccionado != null) {
        txtEditor.setForeground(colorSeleccionado);
    }
    }//GEN-LAST:event_colorLetraActionPerformed

    private void cursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursivaActionPerformed
       java.awt.Font f = txtEditor.getFont();
txtEditor.setFont(f.deriveFont(f.getStyle() ^ java.awt.Font.ITALIC));
    }//GEN-LAST:event_cursivaActionPerformed

    private void cortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortarActionPerformed
        txtEditor.cut();
    }//GEN-LAST:event_cortarActionPerformed

    private void negritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negritaActionPerformed
    java.awt.Font f = txtEditor.getFont();
    txtEditor.setFont(f.deriveFont(f.getStyle() ^ java.awt.Font.BOLD));
    }//GEN-LAST:event_negritaActionPerformed

    private void copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarActionPerformed
        txtEditor.copy();
    }//GEN-LAST:event_copiarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditorDeTexto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenu archivo;
    private javax.swing.JMenu color;
    private javax.swing.JMenuItem colorFondo;
    private javax.swing.JMenuItem colorLetra;
    private javax.swing.JMenuItem copiar;
    private javax.swing.JMenuItem cortar;
    private javax.swing.JMenuItem cursiva;
    private javax.swing.JMenu editar;
    private javax.swing.JMenu fuente;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem negrita;
    private javax.swing.JMenuItem pegar;
    private javax.swing.JMenuItem salir;
    private javax.swing.JTextArea txtEditor;
    // End of variables declaration//GEN-END:variables
}
